### ISSUE TITLE
Can't execute twice?

### ISSUE THREAD

**Issue by sanemat** [pandawing/node-run-yo#56]
I executed once, this worked fine (with errors?). But I executed again, then I got module error

```
> generator-nm5@3.1.3 example /Users/sane/work/js-study/generator-nm5
> run-yo

module.js:341
    throw err;
    ^

Error: Cannot find module 'pify'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/sane/work/js-study/generator-nm5/node_modules/run-yo/node_modules/lnfs/index.js:5:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by sanemat** [comment]
```
$ node --version
v5.5.0
$ npm --version
3.3.12
```

**Comment by sanemat** [comment]
I don't reproduce this.

I think this is `npm v2` -> `npm v3` problem.
